### ISSUE TITLE
Validation Error when adding job

### ISSUE THREAD

**Issue by Sakineee** [Devops-Project20/devops-project#16]
After adding one job, the user is unable to add a second job due to validation error when submitting the form. Please get it resolved.
This issue prevents employers to post multiple jobs.

**Comment by yenyew** [comment]
The issue has been resolved. Please confirm if multiple jobs can be added now.

**Comment by Sakineee** [comment]
looks good. Issue has been resolved, thank you!

**Comment by jiayuuu64** [comment]
Great. Issue have been resolved and multiple jobs can be created now without errors.
