### ISSUE TITLE
Conflict Between Search and Add Job Functionality: Search Becomes Unresponsive When Add Job Form Is Active

### ISSUE THREAD

**Issue by jiayuuu64** [Devops-Project20/devops-project#18]
There is a conflict in the job listing platform. The search functionality becomes unresponsive when the "Add Job" form is opened or actively used. This issue disrupts the user experience, as users cannot search for job listings while simultaneously creating a new job post.

**Comment by Sakineee** [comment]
The issue has been resolved on my side, I have updated codes on my side to prevent this bug from happening. Please double check and close this issue when it has been confirmed resolved. Thank you.

**Comment by yenyew** [comment]
I have also fixed the conflict on my side and pushed the changes to the main branch. Please check if the issue is still occurring.

**Comment by jiayuuu64** [comment]
Thank you. All is good now.
